### ISSUE TITLE
Rspec test for multiple operations not reflected in prompt

### ISSUE THREAD

**Issue by lcurran** [ga-wdi-boston/ruby-rpn-calculator-challenge#6]
Given the wording of the prompt, it never mentions that the calculator should be able to handle expressions with more than one operation, and the examples given for RPN never show a format like the one in rspec where it has three variables followed by multiple operators.  

Rspec test:

```
it 'should evaluate expressions with more than one operation' do
      expect(calc('5 3 2 * + 4 3 * -')).to eq(-1)
      #5 + 3 * 2 - 4 * 3
      expect(calc('9 10 * 2 / 6 4 1 - * -')).to eq(27)
      #9 * 10 / 2 - 6 * (4 - 1)
```

**Comment by RealWeeks** [comment]
@lcurran Thanks for the issue. I agree and added the proper language in commit cebb44f.

**Comment by gaand** [comment]
I believe the test is controlling in this instance and so this addition seems unnecessary.  I would have preferred to chat about this before making a change.

@jrhorn424 Do you think it's necessary to make this explicit in the prompt given the tests test for it?  Shouldn't developers be able to figure this out at this point?

**Comment by RealWeeks** [comment]
This is the only line I wrote `Please note your calculator should be able to handle expressions with more than one operation.` I don't think it changes the instructions aside from clarifying.  I considered it a minor change.

Not an argument, insight into why I updated it without discussion.

**Comment by BenGitsCode** [comment]
Based on this reopening and appearing unresolved, do we have concensus on closing this issue || removing that line? @gaand thoughts?
