### ISSUE TITLE
README.md should say to run `rake test`

### ISSUE THREAD

**Issue by gaand** [ga-wdi-boston/ruby-rpn-calculator-challenge#8]
Not to run `rspec`.

Based on ruby-template.

**Comment by RealWeeks** [comment]
@gaand Updated from template and changed language from `rspec` to `rake test` in commit 5da5435 and commit 31fe8fa79e8cfd7196b3fe5cfcbc5ceacc2736a0. Okay to close?

**Comment by RealWeeks** [comment]
template commit d66ae989e406b0298e271d787bc45a052d865ba0
